spring:
  application:
    name: "eureka"

server:
  port: 3300

management:
  endpoints:
    web.exposure:
      include: routes

eureka:
  client:
    service-url.defaultZone: http://localhost:3300/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
